-- Rootsphere — Phase 4: Hints & AI.
--
-- Confidence-ranked suggestions about people in a tree, generated by Claude
-- (via the `hints` Edge Function) and/or local heuristics. Member-based RLS
-- reuses `is_tree_member()` so every tree member can read/triage its hints.
-- Run AFTER 20260617000000_tree_members.sql.

-- ── Table ──────────────────────────────────────────────────────────────────────

create table if not exists public.hints (
  id                text primary key,                    -- client-generated id
  tree_id           text not null
                       references public.trees (id) on delete cascade,
  owner_id          uuid not null default auth.uid()
                       references auth.users (id) on delete cascade,
  type              text not null default 'missingData',
  title             text not null default '',
  description       text not null default '',
  confidence        int  not null default 50,
  status            text not null default 'pending',
  source            text not null default 'local',
  person_id         text,
  related_person_id text,
  record_id         text,
  field             text,
  suggested_value   text,
  relation          text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create index if not exists hints_tree_id_idx on public.hints (tree_id);
create index if not exists hints_status_idx  on public.hints (tree_id, status);

-- Keep updated_at fresh (reuses set_updated_at() from the tree migration).
drop trigger if exists hints_set_updated_at on public.hints;
create trigger hints_set_updated_at
  before update on public.hints
  for each row execute function public.set_updated_at();

-- ── Row-level security (member-based) ─────────────────────────────────────────

alter table public.hints enable row level security;

drop policy if exists "hints_member_all" on public.hints;
create policy "hints_member_all" on public.hints
  for all
  to authenticated
  using (public.is_tree_member(tree_id))
  with check (public.is_tree_member(tree_id));

-- ── Realtime ──────────────────────────────────────────────────────────────────

alter publication supabase_realtime add table public.hints;
